version: "4"

services:
  lavalink:
    image: fredboat/lavalink:3.7.12
    container_name: music-lavalink
    hostname: lavalink
    restart: unless-stopped
    volumes:
      - ./docker/application.yml:/opt/Lavalink/application.yml:ro
    environment:
      # set Java options here
      - _JAVA_OPTIONS=-Xmx6G
      # set lavalink server port
      - SERVER_PORT=2333
      # set password for lavalink
      - LAVALINK_SERVER_PASSWORD=SomethingJustLikeThis
    networks:
      - lavalink
    expose:
      # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
      - 2333
    ports:
      # you only need this if you want to make your lavalink accessible from outside of containers
      - "2333:2333"
networks:
  # create a lavalink network you can add other containers to, to give them access to Lavalink
  lavalink:
    name: lavalink
